/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MangaEntry = IDL.Record({
  'stableId' : IDL.Nat,
  'title' : IDL.Text,
  'availableChapters' : IDL.Float64,
  'chaptersRead' : IDL.Float64,
  'completed' : IDL.Bool,
  'bookmarks' : IDL.Vec(IDL.Nat),
  'synopsis' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'coverImages' : IDL.Vec(ExternalBlob),
  'rating' : IDL.Float64,
  'alternateTitles' : IDL.Vec(IDL.Text),
  'isBookmarked' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UpdateFields = IDL.Record({
  'stableId' : IDL.Nat,
  'title' : IDL.Opt(IDL.Text),
  'availableChapters' : IDL.Opt(IDL.Float64),
  'chaptersRead' : IDL.Opt(IDL.Float64),
  'completed' : IDL.Opt(IDL.Bool),
  'bookmarks' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'synopsis' : IDL.Opt(IDL.Text),
  'genres' : IDL.Opt(IDL.Vec(IDL.Text)),
  'notes' : IDL.Opt(IDL.Text),
  'coverImages' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'rating' : IDL.Opt(IDL.Float64),
  'alternateTitles' : IDL.Opt(IDL.Vec(IDL.Text)),
  'isBookmarked' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func([MangaEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteGenre' : IDL.Func([IDL.Text], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(MangaEntry)], ['query']),
  'getAllEntriesWithStableIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, MangaEntry))],
      ['query'],
    ),
  'getAllGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAvailableGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [MangaEntry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isReady' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleBookmark' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateAvailableGenres' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateCompletionStatus' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'updateEntry' : IDL.Func([IDL.Nat, UpdateFields], [MangaEntry], []),
  'updateNotes' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'updateRating' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Float64], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MangaEntry = IDL.Record({
    'stableId' : IDL.Nat,
    'title' : IDL.Text,
    'availableChapters' : IDL.Float64,
    'chaptersRead' : IDL.Float64,
    'completed' : IDL.Bool,
    'bookmarks' : IDL.Vec(IDL.Nat),
    'synopsis' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'coverImages' : IDL.Vec(ExternalBlob),
    'rating' : IDL.Float64,
    'alternateTitles' : IDL.Vec(IDL.Text),
    'isBookmarked' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UpdateFields = IDL.Record({
    'stableId' : IDL.Nat,
    'title' : IDL.Opt(IDL.Text),
    'availableChapters' : IDL.Opt(IDL.Float64),
    'chaptersRead' : IDL.Opt(IDL.Float64),
    'completed' : IDL.Opt(IDL.Bool),
    'bookmarks' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'synopsis' : IDL.Opt(IDL.Text),
    'genres' : IDL.Opt(IDL.Vec(IDL.Text)),
    'notes' : IDL.Opt(IDL.Text),
    'coverImages' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'rating' : IDL.Opt(IDL.Float64),
    'alternateTitles' : IDL.Opt(IDL.Vec(IDL.Text)),
    'isBookmarked' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func([MangaEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteGenre' : IDL.Func([IDL.Text], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(MangaEntry)], ['query']),
    'getAllEntriesWithStableIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, MangaEntry))],
        ['query'],
      ),
    'getAllGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAvailableGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [MangaEntry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isReady' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleBookmark' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateAvailableGenres' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateCompletionStatus' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'updateEntry' : IDL.Func([IDL.Nat, UpdateFields], [MangaEntry], []),
    'updateNotes' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'updateRating' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Float64], []),
  });
};

export const init = ({ IDL }) => { return []; };